### ISSUE TITLE
Comments on Gene Page

### ISSUE THREAD

**Issue by engreitz** [IGVF/catalog-front-end-issues#10]
- Could we create a "Predicted Enhancers" section to replace the "Regulatory Regions" section?  Then we can show elements that are predicted to regulate the gene (as on the variant page), rather than just elements that overlap the gene body (which is incomplete/not particularly useful list, I think).  This table could be identical to the Enhancer-Gene Model Predictions table on the Variant Page, except that you query based on the name of the gene rather than location of the variant.

- I'm not sure the "Linked Proteins" section is helpful as a standalone section.  Perhaps instead the Protein ID and hyperlink can be moved to the top left box, along with the GeneCards information.  If left as a standalone section, the title should be changed to "Encoded Proteins" instead of "Linked Proteins".  With the title "Linked Proteins", I was expecting to see things like protein-protein interactions, or genes with related functions, or something like that

- Linked Transcripts table ... Again, title could be different ("Transcripts" instead of "Linked Transcripts")
 
- What is the "Linked Variants" table?  Is this based on Variants that overlap the gene body?  I don't think this is a particularly useful definition. Or, if not, add a column to explain how the Variant was linked to the gene?

**Comment by hitz** [comment]
Agree that elements should be queried from region_gene edges, not just intersected.  That said; having a list of "nearby elements" is not useless (but separate).
