### ISSUE TITLE
Remove EPIraction from E-G prediction results

### ISSUE THREAD

**Issue by engreitz** [IGVF/catalog-front-end-issues#18]
For the "Enhancer-gene predictions" table on the Variant and Gene pages:

Remove "model == ENCODE_EpiRaction" from the displayed results table

**Comment by lidaof** [comment]
Hi Jesse, do you mean for any return results in this query, if model is ENCODE_EpiRaction, don't display them (discard them)?

**Comment by engreitz** [comment]
Correct.  Discard any results where model == ENCODE_EpiRaction
