### ISSUE TITLE
Variant LD table broken

### ISSUE THREAD

**Issue by engreitz** [IGVF/catalog-front-end-issues#19]
I think the variant table is only fetching or displaying the top 50 results for variants in LD . This means that the table ends up missing many variants and sometimes entire ancestries, depending on which 50 come up in the results first.  This makes the table unusable

Other minor corrections to this table:
• Title should be "X# Variants in Linkage Disequilibrium" not "X# Variants in Linkage Disequilibrium**s**"
• Should be default filtered to EUR, and default sorted by "LD (r^2)", not "LD (D')"

**Comment by lidaof** [comment]
I will check with Shane and Pedro
