### ISSUE TITLE
Disambiguation of rsID->SPDI

### ISSUE THREAD

**Issue by engreitz** [IGVF/catalog-front-end-issues#4]
In some cases, a single rsID (which indicates a genomic position) maps to multiple "variants" (3+ alleles at a single site)

In these cases, default behavior should be to go to the SPDI with the highest allele frequency (e.g., currently in "annotations" --> "gnomad_af_total"

For example, rsid rs1250566 maps to 2 spdis:
"spdi": "NC_000010.11:79286695:G:A"
"spdi": "NC_000010.11:79286695:G:T"
The first ("NC_000010.11:79286695:G:A") should be selected because it has higher bravo_af (0.23977 vs null)

In addition, we should add a little box, e.g. on the left-hand side, noting that the rsID was redirected to a particular variant. e.g.:

"Note: Position rsID has multiple alternative alleles:
Showing: NC_000010.11:79286695:G:A   (Allele Frequency: 0.23977)
Others: NC_000010.11:79286695:G:T  (Allele Frequency: null)"

![Image](https://github.com/IGVF/catalog-front-end-issues/assets/3584784/691b8f5f-b751-42d9-ae55-b8cf134100f3)

@lidaof

**Comment by lidaof** [comment]
Thanks Jesse @engreitz !
@shaneliu0 Shane implemented it in local dev version, we will merge to production soon.
<img width="1212" alt="image" src="https://github.com/IGVF/catalog-front-end-issues/assets/102806/cdb3d867-b463-4de2-b538-45debe031e48">
