### ISSUE TITLE
Tables in Variant Page

### ISSUE THREAD

**Issue by engreitz** [IGVF/catalog-front-end-issues#8]
Would it be possible to add functionality to filter tables on any column? 
e.g. for LD page it would be helpful to be able to filter based on Ancestry

Alternatively, just show one ancestry by default and allow selecting a different one

**Comment by mikelove** [comment]
Small note: in e.g. "50 Variants in Linkage Disequilibriums", the word _Disequilibrium_ should not be plural here. You could safely say "LD" also.

**Comment by lidaof** [comment]
will fix that @mikelove @shaneliu0
